LAB 2:
Ex 1 lab 2:
CREATE TABLE TAGS (
	ID NUMBER(3),
	TAGNAME VARCHAR2(30),
	CONSTRAINT pk_id PRIMARY KEY(ID)
	);
	
CREATE TABLE USERS (
	ID NUMBER(3),
	USERNAME VARCHAR2(30),
	PASSWORD VARCHAR2(30),
	CONSTRAINT pk_idu PRIMARY KEY(ID)
	);
	
CREATE TABLE ARTICLES (
	ID NUMBER(3),
	IDUSER NUMBER(3),
	TITLE VARCHAR2(30),
	CONTENT VARCHAR2(30),
	CONSTRAINT pk_ida PRIMARY KEY(ID),
	CONSTRAINT fk_idu FOREIGN KEY(IDUSER) REFERENCES USERS(ID)
	);
	
CREATE TABLE TAGS_ARTICLES (
	IDARTICLE NUMBER(3),
	IDTAG NUMBER(3),
	CONSTRAINT pk_compound PRIMARY KEY(IDARTICLE, IDTAG),
	CONSTRAINT fk_ida FOREIGN KEY(IDARTICLE) REFERENCES ARTICLES(ID),
	CONSTRAINT fk_idt FOREIGN KEY(IDTAG) REFERENCES TAGS(ID)
	);
	
CREATE TABLE COMMENTS (
	ID NUMBER(3),
	ARTICLE_COMMENT VARCHAR2(30),
	IDARTICLE NUMBER(3),
	IDUSER NUMBER(3),
	CONSTRAINT pk_idc PRIMARY KEY(ID),
	CONSTRAINT fk_idac FOREIGN KEY(IDARTICLE) REFERENCES ARTICLES(ID),
	CONSTRAINT fk_iduc FOREIGN KEY(IDUSER) REFERENCES USERS(ID)
	);

Ex 2 lab 2:
CREATE TABLE RECIPES (
	ID_RECIPE NUMBER(3),
	TITLE VARCHAR2(30),
	INSTRUCTIONS VARCHAR2(30),
	CONSTRAINT pk_rec PRIMARY KEY(ID_RECIPE)
	);

CREATE TABLE CATEGORIES (
	ID_CATEGORY NUMBER(3),
	CATEGORY VARCHAR2(30),
	CONSTRAINT pk_cat PRIMARY KEY(ID_CATEGORY)
	);

CREATE TABLE INGREDIENTS (
	ID_INGREDIENT NUMBER(3),
	ID_CATEGORY NUMBER(3),
	INGREDIENT VARCHAR2(30),
	CONSTRAINT pk_ing PRIMARY KEY(ID_INGREDIENT),
	CONSTRAINT fk_cat FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORIES(ID_CATEGORY)
	);
	
CREATE TABLE LINK (
	ID_RECIPE NUMBER(3),
	ID_INGREDIENT NUMBER(3),
	QUANTITY NUMBER(3),
	MU VARCHAR2(30),
	CONSTRAINT pk_compound1 PRIMARY KEY(ID_RECIPE, ID_INGREDIENT),
	CONSTRAINT fk_rec FOREIGN KEY(ID_RECIPE) REFERENCES RECIPES(ID_RECIPE),
	CONSTRAINT fk_ing FOREIGN KEY(ID_INGREDIENT) REFERENCES INGREDIENTS(ID_INGREDIENT)
	);
	
Ex 3 lab 2:
CREATE TABLE PRODUCERS (
	ID_PRODUCER NUMBER(3),
	NAME VARCHAR2(30),
	CONSTRAINT pk_idp PRIMARY KEY(ID_PRODUCER)
	);

CREATE TABLE CAR_TYPES (
	ID_TYPE NUMBER(3),
	TYPES VARCHAR2(30),
	CONSTRAINT pk_idt PRIMARY KEY(ID_TYPE)
	);	
	
CREATE TABLE CARS (
	ID_CAR NUMBER(3),
	ID_PRODUCER NUMBER(3),
	ID_TYPE NUMBER(3),
	REGISTRATION_NO VARCHAR2(30),
	YEARR NUMBER(4),
	CONSTRAINT pk_idcc PRIMARY KEY(ID_CAR),
	CONSTRAINT fk_idpc FOREIGN KEY(ID_PRODUCER) REFERENCES PRODUCERS(ID_PRODUCER),
	CONSTRAINT fk_idtc FOREIGN KEY(ID_TYPE) REFERENCES CAR_TYPES(ID_TYPE)
	);

CREATE TABLE DRIVERS (
	ID_DRIVER NUMBER(3),
	NAME VARCHAR2(30),
	AGE NUMBER(3),
	CONSTRAINT pk_iddd PRIMARY KEY(ID_DRIVER)
	);
	
CREATE TABLE CARS_DRIVERS (
	ID_DRIVER NUMBER(3),
	ID_CAR NUMBER(3),
	DATEE DATE,
	CONSTRAINT pk_compound2 PRIMARY KEY(ID_DRIVER, ID_CAR),
	CONSTRAINT fk_iddcd FOREIGN KEY(ID_DRIVER) REFERENCES DRIVERS(ID_DRIVER),
	CONSTRAINT fk_idccd FOREIGN KEY(ID_CAR) REFERENCES CARS(ID_CAR)
	);
	
CREATE TABLE LICENSES (
	ID_LICENSE NUMBER(3),
	TYPEE VARCHAR2(30),
	CONSTRAINT pk_idl PRIMARY KEY(ID_LICENSE)
	);
	
CREATE TABLE LICENSES_DRIVERS (
	ID_DRIVER NUMBER(3),
	ID_LICENSE NUMBER(3),
	YEARR NUMBER(4),
	CONSTRAINT pk_compound3 PRIMARY KEY(ID_DRIVER, ID_LICENSE),
	CONSTRAINT fk_iddl FOREIGN KEY(ID_DRIVER) REFERENCES DRIVERS(ID_DRIVER),
	CONSTRAINT fk_idll FOREIGN KEY(ID_LICENSE) REFERENCES LICENSES(ID_LICENSE)
	);

Ex 4 lab 2:
CREATE TABLE FLOWER_TYPES (
	ID_TYPE NUMBER(3),
	TYPES VARCHAR2(30),
	CONSTRAINT pk_idf PRIMARY KEY(ID_TYPE)
	);
	
CREATE TABLE FLOWERS (
	ID_FLOWER NUMBER(3),
	NAME VARCHAR2(30),
	PRICE NUMBER(3),
	COLOR VARCHAR2(30),
	QUANTITY NUMBER(3),
	ID_TYPE NUMBER(3),
	CONSTRAINT pk_idff PRIMARY KEY(ID_FLOWER),
	CONSTRAINT fk_idtf FOREIGN KEY(ID_TYPE) REFERENCES FLOWER_TYPES(ID_TYPE)
	);
	
CREATE TABLE BUQUETTE_TYPES (
	ID_TYPE NUMBER(3),
	TYPEE VARCHAR2(30),
	CONSTRAINT pk_idtb PRIMARY KEY(ID_TYPE)
	);
	
CREATE TABLE BUQUETTES (
	ID_BUQUETTE NUMBER(3),
	NAME VARCHAR2(30),
	ID_TYPE NUMBER(3),
	CONSTRAINT pk_idbb PRIMARY KEY(ID_BUQUETTE),
	CONSTRAINT fk_idtb FOREIGN KEY(ID_TYPE) REFERENCES BUQUETTE_TYPES(ID_TYPE)
	);
	
CREATE TABLE FLOWERS_BUQUETTE (
	ID_BUQUETTE NUMBER(3),
	ID_FLOWER NUMBER(3),
	NUMBER_FLOWER NUMBER(3),
	CONSTRAINT pk_compound4 PRIMARY KEY(ID_BUQUETTE, ID_FLOWER),
	CONSTRAINT fk_idbf FOREIGN KEY(ID_BUQUETTE) REFERENCES BUQUETTES(ID_BUQUETTE),
	CONSTRAINT fk_idff FOREIGN KEY(ID_FLOWER) REFERENCES FLOWERS(ID_FLOWER)
	);
	
Ex 5 lab 2:
CREATE TABLE BOOK_TYPES (
	ID_TYPE NUMBER(3),
	TYPEE VARCHAR2(30),
	CONSTRAINT pk_idtbo PRIMARY KEY(ID_TYPE)
	);
	
CREATE TABLE PUBLISHERS (
	ID_PUBLISHER NUMBER(3),
	NAME VARCHAR2(30),
	CONSTRAINT pk_idpp PRIMARY KEY(ID_PUBLISHER)
	);
	
CREATE TABLE BOOKS (
	ID_BOOK NUMBER(3),
	ID_TYPE NUMBER(3),
	ID_PUBLISHER NUMBER(3),
	TITLE VARCHAR2(30),
	NO_PAGES NUMBER(3),
	PUBLISHING_YEAR NUMBER(4),
	CONSTRAINT pk_idbbo PRIMARY KEY(ID_BOOK),
	CONSTRAINT fk_idtbo FOREIGN KEY(ID_TYPE) REFERENCES BOOK_TYPES(ID_TYPE),
	CONSTRAINT fk_idpb FOREIGN KEY(ID_PUBLISHER) REFERENCES PUBLISHERS(ID_PUBLISHER)
	);

CREATE TABLE AUTHORS (
	ID_AUTHORS NUMBER(3),
	FIRSTNAME VARCHAR2(30),
	LASTNAME VARCHAR2(30),
	CONSTRAINT pk_idaa PRIMARY KEY(ID_AUTHORS)
	);
	
CREATE TABLE BOOKS_AUTHORS (
	ID_BOOK NUMBER(3),
	ID_AUTHOR NUMBER(3),
	CONSTRAINT pk_compound5 PRIMARY KEY(ID_BOOK, ID_AUTHOR),
	CONSTRAINT fk_idbba FOREIGN KEY(ID_BOOK) REFERENCES BOOKS(ID_BOOK),
	CONSTRAINT fk_idaba FOREIGN KEY(ID_AUTHOR) REFERENCES AUTHORS(ID_AUTHORS)
	);
	
Ex 6 lab 2:
CREATE TABLE CATEGORIESS (
	ID_CATEGORY NUMBER(3),
	CATEGORY VARCHAR2(30),
	CONSTRAINT pk_idcat PRIMARY KEY(ID_CATEGORY)
	);
	
CREATE TABLE BANDS (
	ID_BAND NUMBER(3),
	NAME VARCHAR2(30),
	CONSTRAINT pk_idba PRIMARY KEY(ID_BAND)
	);
	
CREATE TABLE ALBUMS (
	ID_ALBUM NUMBER(3),
	TITLE VARCHAR2(30),
	YEARR NUMBER(4),
	ID_BAND NUMBER(3),
	CONSTRAINT pk_idal PRIMARY KEY(ID_ALBUM),
	CONSTRAINT fk_idband FOREIGN KEY(ID_BAND) REFERENCES BANDS(ID_BAND)
	);
	
CREATE TABLE SONGS (
	ID_SONG NUMBER(3),
	ID_CATEGORY NUMBER(3),
	ID_ALBUM NUMBER(3),
	TITLE VARCHAR2(30),
	LENGTHH NUMBER(3),
	CONTENT VARCHAR2(30),
	CONSTRAINT pk_ids PRIMARY KEY(ID_SONG),
	CONSTRAINT fk_idcaT FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORIESS(ID_CATEGORY),
	CONSTRAINT fk_idal FOREIGN KEY(ID_ALBUM) REFERENCES ALBUMS(ID_ALBUM)
	);
	
CREATE TABLE ARTISTS (
	ID_ARTIST NUMBER(3),
	ID_BAND NUMBER(3),
	FIRSTNAME VARCHAR2(30),
	LASTNAME VARCHAR2(30),
	FATE_OF_BIRTH DATE,
	CONSTRAINT pk_idar PRIMARY KEY(ID_ARTIST),
	CONSTRAINT fk_idba FOREIGN KEY(ID_BAND) REFERENCES BANDS(ID_BAND)
	);
	
CREATE TABLE COMPOSERS (
	ID_SONG NUMBER(3),
	ID_ARTIST NUMBER(3),
	CONSTRAINT pk_compound6 PRIMARY KEY(ID_SONG, ID_ARTIST),
	CONSTRAINT fk_ids FOREIGN KEY(ID_SONG) REFERENCES SONGS(ID_SONG),
	CONSTRAINT fk_idar FOREIGN KEY(ID_ARTIST) REFERENCES ARTISTS(ID_ARTIST)
	);
	
------
CREATE TABLE DEPARTAMENTE (
	ID_DEPARTAMENT NUMBER(2) NOT NULL,
	DENUMIRE_DEPARTAMENT VARCHAR2(30),
	TELEFON VARCHAR2(10)
	);
	
CREATE TABLE GRILA_SALARIU (
	GRAD NUMBER(2),
	NIVEL_INFERIOR NUMBER,
	NIVEL_SUPERIOR NUMBER
	);
	
CREATE TABLE ANGAJATI (
	ID_ANGAJAT NUMBER(4) NOT NULL,
	NUME VARCHAR2(30),
	PRENUME VARCHAR2(30),
	FUNCTIE VARCHAR2(20),
	ID_SEF NUMBER(4),
	DATA_ANGAJARII DATE DEFAULT SYSDATE,
	SALARIU NUMBER(7,2) DEFAULT 2000,
	COMISION NUMBER(7,2),
	ID_DEPARTAMENT NUMBER
	);
	
column NUME format a20
column PRENUME format a20
column FUNCTIE format a20
column SALARIU format 9999.99
SELECT NUME, PRENUME, FUNCTIE, SALARIU FROM ANGAJATI;